# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/factori.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/factori.proto',
  package='tutorial',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x14protos/factori.proto\x12\x08tutorial\"J\n\tRectangle\x12\x0e\n\x06startX\x18\x01 \x01(\x05\x12\x0e\n\x06startY\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\"<\n\x0bInteraction\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\x17\n\x0finteractionChar\x18\x03 \x01(\t\"\x18\n\x06\x45ntity\x12\x0e\n\x06typeId\x18\x01 \x01(\x05\">\n\x04Tile\x12\"\n\x08\x65ntities\x18\x01 \x03(\x0b\x32\x10.tutorial.Entity\x12\x12\n\ntileTypeId\x18\x02 \x01(\x05\"R\n\x0cViewResponse\x12#\n\x06viewOf\x18\x01 \x01(\x0b\x32\x13.tutorial.Rectangle\x12\x1d\n\x05tiles\x18\x02 \x03(\x0b\x32\x0e.tutorial.Tile\":\n\x0eScreenResponse\x12(\n\x08subViews\x18\x01 \x03(\x0b\x32\x16.tutorial.ViewResponse\"\x1d\n\x05\x43oord\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"Z\n\x0bViewRequest\x12%\n\x08\x66ullView\x18\x01 \x01(\x0b\x32\x13.tutorial.Rectangle\x12$\n\x07oldView\x18\x02 \x01(\x0b\x32\x13.tutorial.Rectangle\"\x07\n\x05\x45mpty2\xcc\x01\n\x0e\x46\x61\x63toryService\x12\x32\n\x08Interact\x12\x15.tutorial.Interaction\x1a\x0f.tutorial.Empty\x12<\n\x0bRequestView\x12\x13.tutorial.Rectangle\x1a\x18.tutorial.ScreenResponse\x12H\n\x11RequestViewStream\x12\x15.tutorial.ViewRequest\x1a\x18.tutorial.ScreenResponse(\x01\x30\x01\x62\x06proto3'
)




_RECTANGLE = _descriptor.Descriptor(
  name='Rectangle',
  full_name='tutorial.Rectangle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='startX', full_name='tutorial.Rectangle.startX', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='startY', full_name='tutorial.Rectangle.startY', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='width', full_name='tutorial.Rectangle.width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='tutorial.Rectangle.height', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=108,
)


_INTERACTION = _descriptor.Descriptor(
  name='Interaction',
  full_name='tutorial.Interaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='tutorial.Interaction.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='tutorial.Interaction.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interactionChar', full_name='tutorial.Interaction.interactionChar', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=170,
)


_ENTITY = _descriptor.Descriptor(
  name='Entity',
  full_name='tutorial.Entity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='typeId', full_name='tutorial.Entity.typeId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=196,
)


_TILE = _descriptor.Descriptor(
  name='Tile',
  full_name='tutorial.Tile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entities', full_name='tutorial.Tile.entities', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tileTypeId', full_name='tutorial.Tile.tileTypeId', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=260,
)


_VIEWRESPONSE = _descriptor.Descriptor(
  name='ViewResponse',
  full_name='tutorial.ViewResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='viewOf', full_name='tutorial.ViewResponse.viewOf', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tiles', full_name='tutorial.ViewResponse.tiles', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=262,
  serialized_end=344,
)


_SCREENRESPONSE = _descriptor.Descriptor(
  name='ScreenResponse',
  full_name='tutorial.ScreenResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subViews', full_name='tutorial.ScreenResponse.subViews', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=346,
  serialized_end=404,
)


_COORD = _descriptor.Descriptor(
  name='Coord',
  full_name='tutorial.Coord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='tutorial.Coord.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='tutorial.Coord.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=435,
)


_VIEWREQUEST = _descriptor.Descriptor(
  name='ViewRequest',
  full_name='tutorial.ViewRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fullView', full_name='tutorial.ViewRequest.fullView', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='oldView', full_name='tutorial.ViewRequest.oldView', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=437,
  serialized_end=527,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='tutorial.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=529,
  serialized_end=536,
)

_TILE.fields_by_name['entities'].message_type = _ENTITY
_VIEWRESPONSE.fields_by_name['viewOf'].message_type = _RECTANGLE
_VIEWRESPONSE.fields_by_name['tiles'].message_type = _TILE
_SCREENRESPONSE.fields_by_name['subViews'].message_type = _VIEWRESPONSE
_VIEWREQUEST.fields_by_name['fullView'].message_type = _RECTANGLE
_VIEWREQUEST.fields_by_name['oldView'].message_type = _RECTANGLE
DESCRIPTOR.message_types_by_name['Rectangle'] = _RECTANGLE
DESCRIPTOR.message_types_by_name['Interaction'] = _INTERACTION
DESCRIPTOR.message_types_by_name['Entity'] = _ENTITY
DESCRIPTOR.message_types_by_name['Tile'] = _TILE
DESCRIPTOR.message_types_by_name['ViewResponse'] = _VIEWRESPONSE
DESCRIPTOR.message_types_by_name['ScreenResponse'] = _SCREENRESPONSE
DESCRIPTOR.message_types_by_name['Coord'] = _COORD
DESCRIPTOR.message_types_by_name['ViewRequest'] = _VIEWREQUEST
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Rectangle = _reflection.GeneratedProtocolMessageType('Rectangle', (_message.Message,), {
  'DESCRIPTOR' : _RECTANGLE,
  '__module__' : 'protos.factori_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Rectangle)
  })
_sym_db.RegisterMessage(Rectangle)

Interaction = _reflection.GeneratedProtocolMessageType('Interaction', (_message.Message,), {
  'DESCRIPTOR' : _INTERACTION,
  '__module__' : 'protos.factori_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Interaction)
  })
_sym_db.RegisterMessage(Interaction)

Entity = _reflection.GeneratedProtocolMessageType('Entity', (_message.Message,), {
  'DESCRIPTOR' : _ENTITY,
  '__module__' : 'protos.factori_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Entity)
  })
_sym_db.RegisterMessage(Entity)

Tile = _reflection.GeneratedProtocolMessageType('Tile', (_message.Message,), {
  'DESCRIPTOR' : _TILE,
  '__module__' : 'protos.factori_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Tile)
  })
_sym_db.RegisterMessage(Tile)

ViewResponse = _reflection.GeneratedProtocolMessageType('ViewResponse', (_message.Message,), {
  'DESCRIPTOR' : _VIEWRESPONSE,
  '__module__' : 'protos.factori_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.ViewResponse)
  })
_sym_db.RegisterMessage(ViewResponse)

ScreenResponse = _reflection.GeneratedProtocolMessageType('ScreenResponse', (_message.Message,), {
  'DESCRIPTOR' : _SCREENRESPONSE,
  '__module__' : 'protos.factori_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.ScreenResponse)
  })
_sym_db.RegisterMessage(ScreenResponse)

Coord = _reflection.GeneratedProtocolMessageType('Coord', (_message.Message,), {
  'DESCRIPTOR' : _COORD,
  '__module__' : 'protos.factori_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Coord)
  })
_sym_db.RegisterMessage(Coord)

ViewRequest = _reflection.GeneratedProtocolMessageType('ViewRequest', (_message.Message,), {
  'DESCRIPTOR' : _VIEWREQUEST,
  '__module__' : 'protos.factori_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.ViewRequest)
  })
_sym_db.RegisterMessage(ViewRequest)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'protos.factori_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.Empty)
  })
_sym_db.RegisterMessage(Empty)



_FACTORYSERVICE = _descriptor.ServiceDescriptor(
  name='FactoryService',
  full_name='tutorial.FactoryService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=539,
  serialized_end=743,
  methods=[
  _descriptor.MethodDescriptor(
    name='Interact',
    full_name='tutorial.FactoryService.Interact',
    index=0,
    containing_service=None,
    input_type=_INTERACTION,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RequestView',
    full_name='tutorial.FactoryService.RequestView',
    index=1,
    containing_service=None,
    input_type=_RECTANGLE,
    output_type=_SCREENRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RequestViewStream',
    full_name='tutorial.FactoryService.RequestViewStream',
    index=2,
    containing_service=None,
    input_type=_VIEWREQUEST,
    output_type=_SCREENRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FACTORYSERVICE)

DESCRIPTOR.services_by_name['FactoryService'] = _FACTORYSERVICE

# @@protoc_insertion_point(module_scope)
